import { useState } from 'react';
import { Users, AlertTriangle, Radio, ShieldCheck } from 'lucide-react';
import { useHealth, useHistory } from '../../hooks/live';
import { useInvestigations } from '../../hooks/simulation';
import { KpiCard } from '../../components/cards/KpiCard';
import { InvestigationSummary } from '../../components/cards/InvestigationSummary';
import { InvestigationTable } from '../../components/tables/InvestigationTable';
import { ConsumptionTrendChart } from '../../components/charts/ConsumptionTrendChart';
import { LiveMeterChart } from '../../components/charts/LiveMeterChart';
import { QueryState } from '../../components/common/QueryState';
import { Select } from '../../components/ui/select';
import { historyPoints } from '../../utils/liveData';

export function Dashboard() {
  const [timeframe, setTimeframe] = useState<'24H' | '7D' | '30D' | '1Y'>('30D');
  const [selectedId, setSelectedId] = useState('');
  const investigations = useInvestigations();
  const health = useHealth();
  const rows = investigations.data ?? [];
  const selected = rows.find(r => r.consumer_id === selectedId) ?? rows.find(r => r.simulated) ?? rows[0];
  const history = useHistory(selected?.consumer_id ?? '');
  const points = historyPoints(history.data ?? [], timeframe).map(p => ({ ...p, baseline: selected?.baseline_kwh ?? null }));
  const ready = investigations.isSuccess;
  return <div className="space-y-6 pb-14">
    <div className="flex flex-wrap items-center justify-between gap-3 bg-white border border-slate-200 px-4 py-3 rounded-md text-xs">
      <div className="flex items-center gap-2"><span className={`w-2.5 h-2.5 rounded-full ${health.data?.status === 'ok' && !health.error ? 'bg-emerald-500' : 'bg-amber-500'}`} /><span className="font-semibold">System Status: {health.error ? 'Unavailable' : health.data?.status === 'ok' ? 'Operational' : 'Checking / degraded'}</span></div>
      <span className="text-slate-500">Automatic updates every 2 seconds · simulated data is labelled</span>
    </div>
    <QueryState error={health.error} onRetry={() => health.refetch()} />
    <QueryState loading={investigations.isLoading} error={investigations.error} onRetry={() => investigations.refetch()} />
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      <KpiCard title="Total Consumers" value={ready ? rows.length : '—'} subtitle="Includes labelled demo copies" icon={<Users className="w-4 h-4" />} />
      <KpiCard title="Live Simulations" value={ready ? rows.filter(r => r.stream_state === 'running').length : '—'} subtitle="Generated by the backend" icon={<Radio className="w-4 h-4" />} />
      <KpiCard title="Requires Review" value={ready ? rows.filter(r => r.requires_review && !['Dismissed', 'Resolved'].includes(r.case_status ?? '')).length : '—'} subtitle="Operational evidence or ML screening" icon={<AlertTriangle className="w-4 h-4 text-amber-600" />} />
      <KpiCard title="Scored Consumers" value={ready ? rows.filter(r => r.prediction).length : '—'} subtitle="Real saved model predictions" icon={<ShieldCheck className="w-4 h-4" />} />
    </div>
    <InvestigationTable rows={rows} />
    {selected && <>
      <label className="block text-xs space-y-2 font-medium">Selected consumer
        <Select aria-label="Consumption consumer" value={selected.consumer_id} onChange={e => setSelectedId(e.target.value)}>{rows.map(r => <option key={r.consumer_id} value={r.consumer_id}>{r.consumer_id}{r.simulated ? ` · ${r.source_consumer_id} (simulated)` : ''}</option>)}</Select>
      </label>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="space-y-4 min-w-0">
          {selected.simulated && <LiveMeterChart id={selected.consumer_id} />}
          <QueryState loading={history.isLoading} error={history.error} onRetry={() => history.refetch()} />
          <ConsumptionTrendChart data={points} timeframe={timeframe} onTimeframeChange={setTimeframe} showBaselineToggle={selected.baseline_kwh !== null} live />
        </div>
        <InvestigationSummary key={selected.consumer_id} record={selected} />
      </div>
    </>}
  </div>;
}
